### ISSUE TITLE
No drops for mod-added ores [1.12

### ISSUE THREAD

**Issue by CplPibald** [abused/SuperOres#1]
Using Super Ores 1.8.3_1.12

Also loaded Immersive Engineering, which adds silver, lead, copper, aluminum, and nickel.

I can find super ores in the world for all of the above types, but breaking them with a diamond pickaxe yields no drops.

Super ores for vanilla ores (coal, iron, redstone) drop their respective ores as expected.

**Comment by alothmanmoe** [comment]
Fixed, releasing on curse right now
