### ISSUE TITLE
SuperOres (superores) has failed to load correctly

### ISSUE THREAD

**Issue by krjencik** [abused/SuperOres#16]
[latest.log](https://github.com/abused/SuperOres/files/7887960/latest.log)

minecraft 1.18.1 forge 39.0.40

superores-2.1.0

**Comment by alothmanmoe** [comment]
Was there anything particular you did before this crash showed up? Or did you just add the mod in?

**Comment by alothmanmoe** [comment]
Issue fixed in version 2.1.1
Currently just waiting on curseforge approval of it :D
