### ISSUE TITLE
Could not load mod: not enough info

### ISSUE THREAD

**Issue by Lebyo** [abused/SuperOres#18]
![image](https://user-images.githubusercontent.com/24213341/160976402-31ecb581-5b3d-4c81-acf7-bdeb4417272c.png)
[crash-2022-03-30_21.18.28-fml.txt](https://github.com/abused/SuperOres/files/8385978/crash-2022-03-30_21.18.28-fml.txt)
[latest.log](https://github.com/abused/SuperOres/files/8385985/latest.log)

**Comment by Lebyo** [comment]
The mod was working fine. I think it may be an interaction with another  mod maybe? It stopped working after some updates to other things, but I don't recall what...

**Comment by Lebyo** [comment]
I believe the problem interaction may lie in a mod called "doggy talents" that recently updated

**Comment by krjencik** [comment]
well, im getting a same screen, but with this mods version 2.1.2 and forge 40.1.19 (im trying minecraft 1.18.2...)

**Comment by CodexAdrian** [comment]
Super ores did not support 1.18.2 at the time, it does now, so this should be fixed
